const GOOGLE_LOGIN = "GOOGLE_LOGIN";
const GOOGLE_LOGIN_PENDING = "GOOGLE_LOGIN_PENDING";
const GOOGLE_LOGIN_FAILURE = "GOOGLE_LOGIN_FAILURE";
const GOOGLE_LOGIN_SUCCESS = "GOOGLE_LOGIN_SUCCESS";

const GOOGLE_LOGOUT = "GOOGLE_LOGOUT";
const GOOGLE_LOGOUT_PENDING = "GOOGLE_LOGOUT_PENDING";
const GOOGLE_LOGOUT_SUCCESS = "GOOGLE_LOGOUT_SUCCESS";
const GOOGLE_LOGOUT_FAILURE = "GOOGLE_LOGOUT_FAILURE";

export {
	GOOGLE_LOGIN,
	GOOGLE_LOGIN_PENDING,
	GOOGLE_LOGIN_FAILURE,
	GOOGLE_LOGIN_SUCCESS,
	GOOGLE_LOGOUT_FAILURE,
	GOOGLE_LOGOUT_PENDING,
	GOOGLE_LOGOUT_SUCCESS,
	GOOGLE_LOGOUT
};
