const GOOGLE_LOGIN_PENDING = "GOOGLE_LOGIN_PENDING";
const GOOGLE_LOGIN_FAILURE = "GOOGLE_LOGIN_FAILURE";
const GOOGLE_LOGIN_SUCCESS = "GOOGLE_LOGIN_SUCCESS";

export { GOOGLE_LOGIN_PENDING, GOOGLE_LOGIN_FAILURE, GOOGLE_LOGIN_SUCCESS };
