const DOWNLOAD_TRANSFORMERS_DATA_PENDING = "DOWNLOAD_TRANSFORMERS_DATA_PENDING";
const DOWNLOAD_TRANSFORMERS_DATA_SUCCESS = "DOWNLOAD_TRANSFORMERS_DATA_SUCCESS";
const DOWNLOAD_TRANSFORMERS_DATA_FAILURE = "DOWNLOAD_TRANSFORMERS_DATA_FAILURE";

export {
	DOWNLOAD_TRANSFORMERS_DATA_PENDING,
	DOWNLOAD_TRANSFORMERS_DATA_SUCCESS,
	DOWNLOAD_TRANSFORMERS_DATA_FAILURE
};
