const UPDATE_NEW_EVENT_TITLE = "UPDATE_NEW_EVENT_TITLE";
const UPDATE_NEW_EVENT_DATE = "UPDATE_NEW_EVENT_DATE";
const UPDATE_NEW_EVENT_START_TIME = "UPDATE_NEW_EVENT_START_TIME";
const UPDATE_NEW_EVENT_END_TIME = "UPDATE_NEW_EVENT_END_TIME";
const CLEAR_NEW_EVENT = "CLEAR_NEW_EVENT";
const CREATE_NEW_EVENT = "CREATE_NEW_EVENT";

export {
	UPDATE_NEW_EVENT_DATE,
	UPDATE_NEW_EVENT_END_TIME,
	UPDATE_NEW_EVENT_START_TIME,
	UPDATE_NEW_EVENT_TITLE,
	CLEAR_NEW_EVENT,
	CREATE_NEW_EVENT
};
