const UPDATE_CURRENT_TRANSFORMER_NAME = "UPDATE_CURRENT_TRANSFORMER_NAME";
const UPDATE_CURRENT_TRANSFORMER_STATUS = "UPDATE_CURRENT_TRANSFORMER_STATUS";
const UPDATE_CURRENT_TRANSFORMER_FACTION = "UPDATE_CURRENT_TRANSFORMER_FACTION";
const UPDATE_CURRENT_TRANSFORMER_SKIN = "UPDATE_CURRENT_TRANSFORMER_SKIN";
const UPDATE_CURRENT_TRANSFORMER_VEHICLE = "UPDATE_CURRENT_TRANSFORMER_VEHICLE";
const ADD_CURRENT_TRANSFORMER_GEAR = "ADD_CURRENT_TRANSFORMER_GEAR";
const REMOVE_CURRENT_TRANSFORMER_GEAR = "REMOVE_CURRENT_TRANSFORMER_GEAR";
const CLEAR_CURRENT_TRANSFORMER = "CLEAR_CURRENT_TRANSFORMER";
const SET_CURRENT_TRANSFORMER = "SET_CURRENT_TRANSFORMER";
const UPDATE_CURRENT_TRANSFORMER_PENDING = "UPDATE_CURRENT_TRANSFORMER_PENDING";
const UPDATE_CURRENT_TRANSFORMER_SUCCESS = "UPDATE_CURRENT_TRANSFORMER_SUCCESS";
const UPDATE_CURRENT_TRANSFORMER_FAILURE = "UPDATE_CURRENT_TRANSFORMER_FAILURE";
const DELETE_CURRENT_TRANSFORMER_PENDING = "DELETE_CURRENT_TRANSFORMER_PENDING";
const DELETE_CURRENT_TRANSFORMER_SUCCESS = "DELETE_CURRENT_TRANSFORMER_SUCCESS";
const DELETE_CURRENT_TRANSFORMER_FAILURE = "DELETE_CURRENT_TRANSFORMER_FAILURE";

export {
	UPDATE_CURRENT_TRANSFORMER_FACTION,
	UPDATE_CURRENT_TRANSFORMER_NAME,
	UPDATE_CURRENT_TRANSFORMER_SKIN,
	UPDATE_CURRENT_TRANSFORMER_STATUS,
	UPDATE_CURRENT_TRANSFORMER_VEHICLE,
	ADD_CURRENT_TRANSFORMER_GEAR,
	REMOVE_CURRENT_TRANSFORMER_GEAR,
	CLEAR_CURRENT_TRANSFORMER,
	SET_CURRENT_TRANSFORMER,
	UPDATE_CURRENT_TRANSFORMER_PENDING,
	UPDATE_CURRENT_TRANSFORMER_FAILURE,
	UPDATE_CURRENT_TRANSFORMER_SUCCESS,
	DELETE_CURRENT_TRANSFORMER_PENDING,
	DELETE_CURRENT_TRANSFORMER_FAILURE,
	DELETE_CURRENT_TRANSFORMER_SUCCESS
};
