const GET_EVENTS = "GET_EVENTS";
const GET_EVENTS_PENDING = "GET_EVENTS_PENDING";
const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";
const GET_EVENTS_FAILURE = "GET_EVENTS_FAILURE";
const UPDATE_EVENT = "UPDATE_EVENT";

export { GET_EVENTS, GET_EVENTS_FAILURE, GET_EVENTS_PENDING, GET_EVENTS_SUCCESS, UPDATE_EVENT };
