const GET_EVENTS = "GET_EVENTS";
const GET_EVENTS_PENDING = "GET_EVENTS_PENDING";
const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";
const GET_EVENTS_FAILURE = "GET_EVENTS_FAILURE";

export { GET_EVENTS, GET_EVENTS_FAILURE, GET_EVENTS_PENDING, GET_EVENTS_SUCCESS };
