const SET_NAME = "SET_NAME";
const SET_STATUS = "SET_STATUS";
const SET_FACTION = "SET_FACTION";
const SET_SKIN = "SET_SKIN";
const SET_VEHICLE = "SET_VEHICLE";
const SET_GEAR = "SET_GEAR";
const CREATE_NEW_TRANSFORMER = "CREATE_NEW_TRANSFORMER";

export {
	SET_NAME,
	SET_FACTION,
	SET_GEAR,
	SET_STATUS,
	SET_SKIN,
	SET_VEHICLE,
	CREATE_NEW_TRANSFORMER
};
