const SET_NAME = "SET_NAME";
const SET_STATUS = "SET_STATUS";
const SET_FACTION = "SET_FACTION";
const SET_SKIN = "SET_SKIN";
const SET_VEHICLE = "SET_VEHICLE";
const SET_GEAR = "SET_GEAR";
const UNSET_GEAR = "UNSET_GEAR";
const CREATE_DEFAULT_TRANSFORMER = "CREATE_DEFAULT_TRANSFORMER";
const CREATE_NEW_TRANSFORMER_PENDING = "CREATE_NEW_TRANSFORMER_PENDING";
const CREATE_NEW_TRANSFORMER_SUCCESS = "CREATE_NEW_TRANSFORMER_SUCCESS";
const CREATE_NEW_TRANSFORMER_FAILURE = "CREATE_NEW_TRANSFORMER_FAILURE";

export {
	SET_NAME,
	SET_FACTION,
	SET_GEAR,
	UNSET_GEAR,
	SET_STATUS,
	SET_SKIN,
	SET_VEHICLE,
	CREATE_DEFAULT_TRANSFORMER,
	CREATE_NEW_TRANSFORMER_PENDING,
	CREATE_NEW_TRANSFORMER_SUCCESS,
	CREATE_NEW_TRANSFORMER_FAILURE
};
