const UPDATE_CURRENT_EVENT_TITLE = "UPDATE_CURRENT_EVENT_TITLE";
const UPDATE_CURRENT_EVENT_DATE = "UPDATE_CURRENT_EVENT_DATE";
const UPDATE_CURRENT_EVENT_START_TIME = "UPDATE_CURRENT_EVENT_START_TIME";
const UPDATE_CURRENT_EVENT_END_TIME = "UPDATE_CURRENT_EVENT_END_TIME";
const CLEAR_CURRENT_EVENT = "CLEAR_CURRENT_EVENT";
const SET_CURRENT_EVENT = "SET_CURRENT_EVENT";
const UPDATE_CURRENT_EVENT_PENDING = "UPDATE_CURRENT_EVENT_PENDING";
const UPDATE_CURRENT_EVENT_SUCCESS = "UPDATE_CURRENT_EVENT_SUCCESS";
const UPDATE_CURRENT_EVENT_FAILURE = "UPDATE_CURRENT_EVENT_FAILURE";

export {
	UPDATE_CURRENT_EVENT_DATE,
	UPDATE_CURRENT_EVENT_TITLE,
	UPDATE_CURRENT_EVENT_END_TIME,
	UPDATE_CURRENT_EVENT_START_TIME,
	CLEAR_CURRENT_EVENT,
	SET_CURRENT_EVENT,
	UPDATE_CURRENT_EVENT_PENDING,
	UPDATE_CURRENT_EVENT_SUCCESS,
	UPDATE_CURRENT_EVENT_FAILURE
};
