const UPDATE_CURRENT_TRANSFORMER_NAME = "UPDATE_CURRENT_TRANSFORMER_NAME";
const UPDATE_CURRENT_TRANSFORMER_STATUS = "UPDATE_CURRENT_TRANSFORMER_STATUS";
const UPDATE_CURRENT_TRANSFORMER_FACTION = "UPDATE_CURRENT_TRANSFORMER_FACTION";
const UPDATE_CURRENT_TRANSFORMER_SKIN = "UPDATE_CURRENT_TRANSFORMER_SKIN";
const UPDATE_CURRENT_TRANSFORMER_VEHICLE = "UPDATE_CURRENT_TRANSFORMER_VEHICLE";
const ADD_CURRENT_TRANSFORMER_GEAR = "ADD_CURRENT_TRANSFORMER_GEAR";
const REMOVE_CURRENT_TRANSFORMER_GEAR = "REMOVE_CURRENT_TRANSFORMER_GEAR";
const CLEAR_CURRENT_TRANSFORMER = "CLEAR_CURRENT_TRANSFORMER";
const SET_CURRENT_TRANSFORMER = "SET_CURRENT_TRANSFORMER";

export {
	UPDATE_CURRENT_TRANSFORMER_FACTION,
	UPDATE_CURRENT_TRANSFORMER_NAME,
	UPDATE_CURRENT_TRANSFORMER_SKIN,
	UPDATE_CURRENT_TRANSFORMER_STATUS,
	UPDATE_CURRENT_TRANSFORMER_VEHICLE,
	ADD_CURRENT_TRANSFORMER_GEAR,
	REMOVE_CURRENT_TRANSFORMER_GEAR,
	CLEAR_CURRENT_TRANSFORMER,
	SET_CURRENT_TRANSFORMER
};
