const ADD_TRANSFORMER = "ADD_TRANSFORMER";
const ADD_TRANSFORMERS = "ADD_TRANSFORMERS";
const REMOVE_TRANSFORMER = "REMOVE_TRANSFORMER";
const UPDATE_TRANSFORMER = "UPDATE_TRANSFROMER";

export { ADD_TRANSFORMER, REMOVE_TRANSFORMER, ADD_TRANSFORMERS, UPDATE_TRANSFORMER };
