const ADD_TRANSFORMER = "ADD_TRANSFORMER";
const ADD_TRANSFORMERS = "ADD_TRANSFORMERS";
const REMOVE_TRANSFORMER = "REMOVE_TRANSFORMER";

export { ADD_TRANSFORMER, REMOVE_TRANSFORMER, ADD_TRANSFORMERS };
